#!/bin/sh

fileroot='ROOT DRUPAL DIRECTORY'
backuproot='BACKUP DIRECTORY'

dow=`/bin/date +%w`
dom=`/bin/date +%d`

if [ $dow -eq 3 -o $dow -eq 5 ]
then
tar -C $fileroot -czf $backuproot/sites-default-files-wf`/bin/date +%Y%m%d`.tar.gz sites/default/files
tar -C $fileroot -czf $backuproot/sites-all-wf`/bin/date +%Y%m%d`.tar.gz sites/all
else

        if [ $dow -eq 1 ]
        then
        tar -C $fileroot -czf $backuproot/sites-default-files-weekly`/bin/date +%Y%m%d`.tar.gz sites/default/files
        tar -C $fileroot -czf $backuproot/sites-all-weekly`/bin/date +%Y%m%d`.tar.gz sites/all
        rm $backuproot/sites-default-files-wf*
        rm $backuproot/sites-all-wf*
        fi
fi

if [ $dom = '01' ]

then
mv $backuproot/sites-default-files-weekly`/bin/date --date='last monday' +%Y%m%d`.tar.gz $backuproot/sites-default-files-monthly`/bin/date --date='last monday' +%Y%m%d`.tar.gz
mv $backuproot/sites-all-weekly`/bin/date --date='last monday' +%Y%m%d`.tar.gz $backuproot/sites-all-monthly`/bin/date --date='last monday' +%Y%m%d`.tar.gz
        rm $backuproot/sites-default-files-weekly*
        rm $backuproot/sites-all-weekly*
fi
