#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ -z $1 ] || [ ! -r $DIR/$1 ]
  then
    configfile="$DIR/backup.cfg"
  else
    configfile="$DIR/$1"
fi

source "$configfile"
dow=`/bin/date +%w`
dom=`/bin/date +%d`
month=`/bin/date +%m`

if [ "$2" = 'firstrun' ] || ([ -z $2 ] && [ "$1" = 'firstrun' ])
  then
    dom='01'
    month='01'
    firstrun=TRUE
fi

export PASSPHRASE=$passphrase
if [ ! -z $s3accesskey ]
  then
    export AWS_ACCESS_KEY_ID=$s3accesskey
    export AWS_SECRET_ACCESS_KEY=$s3secret
fi

if [ $dom = '01' ]
  then
    lastrun=`duplicity full --name $siteid $fileroot file://$local/files`
    lastrun+=$'\n'`duplicity remove-all-but-n-full 6 --name $siteid --force file://$local/files`
    lastrun+=$'\n'`duplicity remove-all-inc-of-but-n-full 2 --name $siteid --force file://$local/files`
    if [ ! -z $remote ]
      then
        lastrun+=$'\n'`duplicity full --name $siteid-remote-files $fileroot $remote/files`
        lastrun+=$'\n'`duplicity remove-all-but-n-full 6 --name $siteid-remote-files --force $remote/files`
        lastrun+=$'\n'`duplicity remove-all-inc-of-but-n-full 2 --name $siteid-remote-files --force $remote/files`
    fi
  else
    lastrun=`duplicity incremental --name $siteid $fileroot file://$local/files`
    if [ ! -z $remote ]
      then
        lastrun+=$'\n'`duplicity incremental --name $siteid-remote-files $fileroot $remote/files`
    fi
fi

mkdir -p $local/db/daily
mkdir -p $local/db/weekly
mkdir -p $local/db/monthly

rm -f $local/db/$dbname"daily"*.sql
if [ -z $loginpath ]
  then
    mysqldump --routines -u $dbuser -p$dbpass $dbname > $local/db/$dbname"daily"`/bin/date +%Y%m%d`.sql
  else
    mysqldump --routines --login-path=$loginpath $dbname > $local/db/$dbname"daily"`/bin/date +%Y%m%d`.sql
fi

tar -C $local/db -czf $local/db/daily/$dbname"daily"`/bin/date +%Y%m%d`.sql.tar.gz $dbname"daily"`/bin/date +%Y%m%d`.sql
chmod 600 $local/db/$dbname"daily"`/bin/date +%Y%m%d`.sql
chmod 600 $local/db/daily/$dbname"daily"`/bin/date +%Y%m%d`.sql.tar.gz

if [ ! -z $cmsdbname ]
  then
    rm -f $local/db/$cmsdbname"daily"*.sql
    if [ -z $loginpath ]
      then
        mysqldump -u $dbuser -p$dbpass $cmsdbname > $local/db/$cmsdbname"daily"`/bin/date +%Y%m%d`.sql
      else
        mysqldump --login-path=$loginpath $cmsdbname > $local/db/$cmsdbname"daily"`/bin/date +%Y%m%d`.sql
    fi

    tar -C $local/db -czf $local/db/daily/$cmsdbname"daily"`/bin/date +%Y%m%d`.sql.tar.gz $cmsdbname"daily"`/bin/date +%Y%m%d`.sql
    chmod 600 $local/db/$cmsdbname"daily"`/bin/date +%Y%m%d`.sql
    chmod 600 $local/db/daily/$cmsdbname"daily"`/bin/date +%Y%m%d`.sql.tar.gz
fi

if [ ! -z $remote ]
  then
    if [ $dom = '01' ]
      then
        lastrun+=$'\n'`duplicity full --name $siteid-db-daily $local/db/daily $remote/db/daily`
      else
        lastrun+=$'\n'`duplicity incremental --name $siteid-db-daily $local/db/daily $remote/db/daily`
    fi
fi

if [ $dow -eq 0 ]
  then
    mv $local/db/daily/$dbname"daily"`/bin/date +%Y%m%d`.sql.tar.gz $local/db/weekly/$dbname"weekly"`/bin/date +%Y%m%d`.sql.tar.gz
    rm -f $local/db/daily/$dbname"daily"*

    if [ ! -z $cmsdbname ]
      then
        mv $local/db/daily/$cmsdbname"daily"`/bin/date +%Y%m%d`.sql.tar.gz $local/db/weekly/$cmsdbname"weekly"`/bin/date +%Y%m%d`.sql.tar.gz
        rm -f $local/db/daily/$cmsdbname"daily"*
    fi
fi

if [ $dom = '01' ]
  then
    if [ -z $firstrun ]
      then
        mv $local/db/weekly/$dbname"weekly"`/bin/date --date='last sunday' +%Y%m%d`.sql.tar.gz $local/db/monthly/$dbname"monthly"`/bin/date --date='last sunday' +%Y%m%d`.sql.tar.gz
        rm -f $local/db/weekly/$dbname"weekly"*

        if [ ! -z $cmsdbname ]
          then
            mv $local/db/weekly/$cmsdbname"weekly"`/bin/date --date='last sunday' +%Y%m%d`.sql.tar.gz $local/db/monthly/$cmsdbname"monthly"`/bin/date --date='last sunday' +%Y%m%d`.sql.tar.gz
            rm -f $local/db/weekly/$cmsdbname"weekly"*
        fi
    fi

    if [ ! -z $remote ]
      then
        lastrun+=$'\n'`duplicity remove-all-but-n-full 2 --name $siteid-db-daily --force $remote/db/daily`
        lastrun+=$'\n'`duplicity remove-all-but-n-full 1 --name $siteid-db-monthly --force $remote/db/monthly`

        if [ $month = '01' ]
          then
            lastrun+=$'\n'`duplicity full --name $siteid-db-monthly $local/db/monthly $remote/db/monthly`
          else
            lastrun+=$'\n'`duplicity incremental --name $siteid-db-monthly $local/db/monthly $remote/db/monthly`
        fi
    fi
fi
unset PASSPHRASE
if [ ! -z $s3accesskey ]
  then
    unset AWS_ACCESS_KEY_ID
    unset AWS_SECRET_ACCESS_KEY
fi

echo "$lastrun" > $DIR/lastrun
